apiVersion: apps/v1
kind: Deployment
metadata:
  name: liberty-deployment
  labels:
    app: liberty
spec:
  selector:
    matchLabels:
      app: liberty
  template:
    metadata:
      labels:
        app: liberty
    spec:
      containers:
      - name: liberty-container
        image: 172.30.1.1:5000/liberty/java_micro_svc:latest
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: liberty-service
spec:
  selector:
    app: liberty
  ports:
  - protocol: TCP
    port: 9080
---
apiVersion: v1
kind: Route
metadata:
  name: liberty-route
spec:
  to:
    kind: Service
    name: liberty-service
